# FlatJsonDB
:toc:

## Main goals

* Simple straight forward in process database
* Store json and other text files hierarchical in the file system
* Integrated apache lucene support
* Mapping and handling relations between entities, including lazy loading
* In process database
* Support versioning via GIT(jgit), including support for submodules to get a distributed storage that can be synced

## Quickstart

### Create an entity

We create a new entity which has the following properties:

* a name as natural id
* a string attribute
* simple auditing times like *creationTime* and *updateTime*

[source,java]
----
@Entity
public class ExampleEntity extends NamedEntity {
  private String attribute;

  protected ExampleEntity() {//jackson needs default constructor
    super(null);
  }

  public ExampleEntity(String name) {
    super(name);
  }

  public String getAttribute() {
    return attribute;
  }

  public ExampleEntity setAttribute(String attribute) {
    this.attribute = attribute;
    return this;
  }
}
----

### Setup the repository and sessionfactory
[source,java]
----
//open a repository with a java.nio.Path
Repository repository = new Repository(Paths.get("myRepoPath"));

//open a new session factory
//the factory needs at least one repository and a package to scan or 1-n entity classes
//a factory needs to be closed again to release resources(mainly lucene index)
SessionFactory factory = new SessionFactory(repository, ExampleEntity.class);

/*
 * execute some code
 */

factory.close();//if we don't use a try-with-resource block we need to close the factory manually
----


### Persist modify and delete
[source,java]
----
//persist an entity
factory.transactedSession(session -> {
  ExampleEntity entity = new ExampleEntity("Hello world!");
  assert entity.getId() == null;
  session.persist(entity);
  assert entity.getId() != null;//the unique id is written into the entity with the persist call
});

//modify entity
factory.transactedSession(session -> {
  ExampleEntity entity = session.findByNaturalId(ExampleEntity.class, "Hello world!");
  entity.setAttribute("Coffee");

  ExampleEntity entity2 = session.findByNaturalId(ExampleEntity.class, "Hello world!");
  assert entity==entity2;//same instance always returned
});

//read entity
ExampleEntity entity = factory.transactedSessionRead(session -> session.findByNaturalId(ExampleEntity.class, "Hello world!"));
assert "Coffee".equals(entity.getAttribute());//entity is now detached but can still be used.

//delete enity again
factory.transactedSession(session -> {
  ExampleEntity reloaded = session.findByNaturalId(ExampleEntity.class, "Hello world!");
  session.remove(reloaded);
});
----

The contents look like this:
[source,shell]
----
scar@scar:~$ cd /tmp/myRepoPath/
scar@scar:/tmp/myRepoPath$ ls
ExampleEntity
scar@scar:/tmp/myRepoPath$ cd ExampleEntity/
scar@scar:/tmp/myRepoPath/ExampleEntity$ ls
Hello_world.json
scar@scar:/tmp/myRepoPath/ExampleEntity$ cat Hello_world.json
{
  "de.ks.flatadocdb.integration.ExampleEntity" : {
    "version" : 1,
    "id" : "720ce395f0a0a151f198877bd9122257db55cdbe",
    "creationTime" : [ 2015, 12, 6, 9, 28, 59, 50000000 ],
    "updateTime" : [ 2015, 12, 6, 9, 29, 9, 858000000 ],
    "name" : "Hello world!",
    "attribute" : "Coffee"
  }
}
----

### Complete code
[source,java]
----
  @Test
  public void testExample() throws Exception {
    //open a repository with a java.nio.Path
    Repository repository = new Repository(myRepoPath);

    //open a new session factory
    //the factory needs at least one repository and a package to scan or 1-n entity classes
    //a factory needs to be closed again to release resources(mainly lucene index)
    try (SessionFactory factory = new SessionFactory(repository, ExampleEntity.class)) {
      factory.transactedSession(session -> {
        ExampleEntity entity = new ExampleEntity("Hello world!");
        assert entity.getId() == null;
        session.persist(entity);
        assert entity.getId() != null;//the unique id is written into the entity with the persist call
      });

      //modify entity
      factory.transactedSession(session -> {
        ExampleEntity entity = session.findByNaturalId(ExampleEntity.class, "Hello world!");
        entity.setAttribute("Coffee");

        ExampleEntity entity2 = session.findByNaturalId(ExampleEntity.class, "Hello world!");
        assert entity==entity2;//same instance always returned
      });

      //read entity
      ExampleEntity entity = factory.transactedSessionRead(session -> session.findByNaturalId(ExampleEntity.class, "Hello world!"));
      assert "Coffee".equals(entity.getAttribute());//entity is now detached but can still be used.

      //delete enity again
      factory.transactedSession(session -> {
        ExampleEntity reloaded = session.findByNaturalId(ExampleEntity.class, "Hello world!");
        session.remove(reloaded);
      });
    }
//    factory.close(); if we don't use a try-with-resource block we need to close the factory manually
  }
----


## Components

The flatjsondb consists of one or more repositories. +
All repository entries are entities which are registered at a global metamodel. +
Each repository has its own indexes, including the lucene index for searching. +

### Repository

A repository is generally a folder on your filesystem containing a bunch of json/text or other files which are mapped as entities.
It might look like the following:

[source,bash]
-----
scar@scar:/tmp/tempRepo$ pwd
/tmp/tempRepo

scar@scar:/tmp/tempRepo$ ls -lA
total 8
drwxr-xr-x 2 scar scar 4096 Dec  6 07:58 .lucene
drwxr-xr-x 2 scar scar 4096 Dec  6 07:58 .index
drwxr-xr-x 2 scar scar 4096 Dec  6 07:58 .git
drwxr-xr-x 2 scar scar 4096 Dec  6 07:58 TestEntity

scar@scar:/tmp/tempRepo$ cd TestEntity/
scar@scar:/tmp/tempRepo/TestEntity$ ls -lA
total 4
-rw-r--r-- 1 scar scar 262 Dec  6 07:58 blubber.json

scar@scar:/tmp/tempRepo/TestEntity$ cat blubber.json
{
  "de.ks.flatadocdb.metamodel.TestEntity" : {
    "version" : 1,
    "id" : "3708a8ca06b62afd2d3d9b1039702b5b61e59e40",
    "creationTime" : [ 2015, 12, 6, 7, 58, 27, 909000000 ],
    "updateTime" : null,
    "name" : "blubber",
    "attribute" : "Steak"
  }
}
-----

In addition to the entities it contains the index files:

* .git git repository
* .lucene lucene index files
* .index faltadocdb index used to prevent file system scanning and parsing at startup.

As a repository is manged by git you can use it in a distributed way: +
For example you can have a clone on your local computer and a seperate one on a notebook and sync both via wlan.+
Or you can manage one main clone on a cloud storage and push to it from different machines. +

Different repositories can be used eg. for private, family or work stuff.

### Entity

An entity is any java class annotated with *@Entity*.

[source,java]
@Entity
public class TestEntity extends NamedEntity {
...

As you can see we already provide some base classes (NamedEntity and BaseEntity) you can extend from.
Those are just suggestions, you can always use the annotations to map your own entities.

An entity has to

#### Lifecycle callbacks

#### Relations

### Session

### LuceneIndex


